# Request a state change from a packml state machine.  The command set is based
# on the PackML summarized here:
# https://omac.org/workgroups/packml-unitmachine-implementation-guide/
# The response is returned as soon as the request is accepted, but not necessarily
# when the state changes
#
# Enumeration values are based upon tag guidelines, here:
# https://omac.org/workgroups/packml-unitmachine-implementation-guide/


# Values defined in tag naming guidelines
int8 NO_COMMAND=0
int8 RESET=1
int8 START=2
int8 STOP=3
int8 HOLD=4
int8 UNHOLD=5
int8 SUSPEND=6
int8 UNSUSPEND=7
int8 ABORT=8
int8 CLEAR=9

int8 command
---
# State machine response
bool success         # True if command has been accepted

int8 SUCCESS = 1
int8 INVALID_TRANSITION_REQUEST = -1
int8 UNRECOGNIZED_REQUEST = -2
int8 error_code       # Error code if command has been rejected

string message        # Message for display (only for human reading)
